package com.usercrud.model;

import java.sql.Timestamp;

/**
 * User Model (POJO - Plain Old Java Object)
 *
 * Represents a single row of the "users" table in the database.
 * This class has no business logic - it is purely a data holder
 * that is passed between the DAO, Servlet, and JSP layers (MVC pattern).
 */
public class User {

    // ---- Fields (map directly to table columns) ----
    private int id;
    private String name;
    private String email;
    private String password;
    private String phone;
    private String address;
    private Timestamp createdAt;

    /**
     * No-argument constructor.
     * Required so the object can be created and populated
     * step by step using setters (e.g. when reading a ResultSet).
     */
    public User() {
    }

    /**
     * Constructor used when INSERTING a new user
     * (id and createdAt are generated by the database, so they are excluded).
     */
    public User(String name, String email, String password, String phone, String address) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
    }

    /**
     * Full constructor used when READING a user back from the database.
     */
    public User(int id, String name, String email, String password,
                String phone, String address, Timestamp createdAt) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
        this.createdAt = createdAt;
    }

    // ---- Getters and Setters ----

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
